prefix2 = "miko"

command_dict = {
    "airkiss": "Send an air kiss 😘",
    "angrystare": "Stare angrily 👿",
    "bite": "Playfully bite someone 😬",
    "bleh": "Express disgust 😝",
    "blush": "Blush with embarrassment ☺️",
    "brofist": "Give a brofist 👊",
    "celebrate": "Celebrate something 🎉",
    "cheers": "Cheers to something 🥂",
    "clap": "Give a round of applause 👏",
    "confused": "Show confusion 🤔",
    "cool": "Be cool 😎",
    "cry": "Cry 😢",
    "cuddle": "Cuddle with someone 🤗",
    "dance": "Dance 💃🕺",
    "drool": "Drool over something delicious 🤤",
    "evillaugh": "Laugh evilly 😈",
    "facepalm": "Express frustration with a facepalm 🤦‍♂️",
    "handhold": "Hold someone's hand 👫",
    "happy": "Be happy 😄",
    "headbang": "Headbang to the music 🤘",
    "hug": "Give a warm hug 🤗",
    "kiss": "Give a kiss 💋",
    "laugh": "Laugh out loud 😂",
    "lick": "Lick something 👅",
    "love": "Express love ❤️",
    "mad": "Be mad 😡",
    "nervous": "Feel nervous 😬",
    "no": "Say no 🚫",
    "nom": "Nom on something delicious 🍽️",
    "nosebleed": "Have a nosebleed 👃💧",
    "nuzzle": "Nuzzle affectionately 🐾",
    "nyah": "Say 'Nyah!' 😸",
    "pat": "Pat someone or something 🐾",
    "peek": "Peek discreetly 👀",
    "pinch": "Pinch someone or something 👌",
    "poke": "Playfully poke someone",
    "pout": "Pout with displeasure 😞",
    "punch": "Punch something or someone 👊",
    "roll": "Roll your eyes sarcastically 🙄",
    "run": "Run fast! 🏃",
    "sad": "Feel sad 😔",
    "scared": "Feel scared 😱",
    "shrug": "Shrug your shoulders 🤷",
    "shy": "Be shy ☺️",
    "sigh": "Sigh in exasperation 😔",
    "sip": "Take a sip of a drink ☕",
    "slap": "Give a slap to someone or something ✋",
    "sleep": "Go to sleep 😴",
    "slowclap": "Give a sarcastic slow clap 👏",
    "smack": "Smack someone or something 👋",
    "smile": "Smile 😃",
    "smug": "Look smug 😏",
    "sneeze": "Sneeze 🤧",
    "sorry": "Apologize and say sorry 🙁",
    "stare": "Stare intensely 👀",
    "stop": "Stop ✋",
    "surprised": "Look surprised 😲",
    "sweat": "Sweat nervously 😅",
    "thumbsup": "Give a thumbs up 👍",
    "tickle": "Tickle someone or something 😄",
    "tired": "Feel tired 😴",
    "wave": "Wave hello or goodbye 👋",
    "wink": "Wink 😉",
    "woah": "Express 'Woah!' in amazement 😮",
    "yawn": "Yawn 😴",
    "yay": "Celebrate with 'Yay!' 🎉",
    "yes": "Say 'Yes' 👍"
}

keys = [k for k in command_dict.keys()]


colors = {
    'DEFAULT': 0x000000,
    'WHITE': 0xFFFFFF,
    'AQUA': 0x1ABC9C,
    'GREEN': 0x2ECC71,
    'BLUE': 0x3498DB,
    'PURPLE': 0x9B59B6,
    'LUMINOUS_VIVID_PINK': 0xE91E63,
    'GOLD': 0xF1C40F,
    'ORANGE': 0xE67E22,
    'RED': 0xE74C3C,
    'GREY': 0x95A5A6,
    'NAVY': 0x34495E,
    'DARK_AQUA': 0x11806A,
    'DARK_GREEN': 0x1F8B4C,
    'DARK_BLUE': 0x206694,
    'DARK_PURPLE': 0x71368A,
    'DARK_VIVID_PINK': 0xAD1457,
    'DARK_GOLD': 0xC27C0E,
    'DARK_ORANGE': 0xA84300,
    'DARK_RED': 0x992D22,
    'DARK_GREY': 0x979C9F,
    'DARKER_GREY': 0x7F8C8D,
    'LIGHT_GREY': 0xBCC0C0,
    'DARK_NAVY': 0x2C3E50,
    'BLURPLE': 0x7289DA,
    'GREYPLE': 0x99AAB5,
    'DARK_BUT_NOT_BLACK': 0x2C2F33,
    'NOT_QUITE_BLACK': 0x23272A
}
